package org.greenpole.hibernate.entity;
// Generated 29-May-2015 21:21:44 by Hibernate Tools 4.3.1



/**
 * AdministratorPostalAddressId generated by hbm2java
 */
public class AdministratorPostalAddressId  implements java.io.Serializable {


     private int administratorId;
     private String addressLine1;
     private String state;
     private String country;

    public AdministratorPostalAddressId() {
    }

    public AdministratorPostalAddressId(int administratorId, String addressLine1, String state, String country) {
       this.administratorId = administratorId;
       this.addressLine1 = addressLine1;
       this.state = state;
       this.country = country;
    }
   
    public int getAdministratorId() {
        return this.administratorId;
    }
    
    public void setAdministratorId(int administratorId) {
        this.administratorId = administratorId;
    }
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AdministratorPostalAddressId) ) return false;
		 AdministratorPostalAddressId castOther = ( AdministratorPostalAddressId ) other; 
         
		 return (this.getAdministratorId()==castOther.getAdministratorId())
 && ( (this.getAddressLine1()==castOther.getAddressLine1()) || ( this.getAddressLine1()!=null && castOther.getAddressLine1()!=null && this.getAddressLine1().equals(castOther.getAddressLine1()) ) )
 && ( (this.getState()==castOther.getState()) || ( this.getState()!=null && castOther.getState()!=null && this.getState().equals(castOther.getState()) ) )
 && ( (this.getCountry()==castOther.getCountry()) || ( this.getCountry()!=null && castOther.getCountry()!=null && this.getCountry().equals(castOther.getCountry()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAdministratorId();
         result = 37 * result + ( getAddressLine1() == null ? 0 : this.getAddressLine1().hashCode() );
         result = 37 * result + ( getState() == null ? 0 : this.getState().hashCode() );
         result = 37 * result + ( getCountry() == null ? 0 : this.getCountry().hashCode() );
         return result;
   }   


}


