package org.greenpole.hibernate.entity;
// Generated 29-May-2015 07:34:19 by Hibernate Tools 4.3.1



/**
 * AdministratorHolderId generated by hbm2java
 */
public class AdministratorHolderId  implements java.io.Serializable {


     private int administratorId;
     private int holderId;

    public AdministratorHolderId() {
    }

    public AdministratorHolderId(int administratorId, int holderId) {
       this.administratorId = administratorId;
       this.holderId = holderId;
    }
   
    public int getAdministratorId() {
        return this.administratorId;
    }
    
    public void setAdministratorId(int administratorId) {
        this.administratorId = administratorId;
    }
    public int getHolderId() {
        return this.holderId;
    }
    
    public void setHolderId(int holderId) {
        this.holderId = holderId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AdministratorHolderId) ) return false;
		 AdministratorHolderId castOther = ( AdministratorHolderId ) other; 
         
		 return (this.getAdministratorId()==castOther.getAdministratorId())
 && (this.getHolderId()==castOther.getHolderId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAdministratorId();
         result = 37 * result + this.getHolderId();
         return result;
   }   


}


