package org.greenpole.hibernate.entity;
// Generated 29-May-2015 21:21:44 by Hibernate Tools 4.3.1



/**
 * AdministratorEmailAddress generated by hbm2java
 */
public class AdministratorEmailAddress  implements java.io.Serializable {


     private AdministratorEmailAddressId id;
     private Long version;
     private Administrator administrator;
     private Boolean isPrimary;

    public AdministratorEmailAddress() {
    }

	
    public AdministratorEmailAddress(AdministratorEmailAddressId id, Administrator administrator) {
        this.id = id;
        this.administrator = administrator;
    }
    public AdministratorEmailAddress(AdministratorEmailAddressId id, Administrator administrator, Boolean isPrimary) {
       this.id = id;
       this.administrator = administrator;
       this.isPrimary = isPrimary;
    }
   
    public AdministratorEmailAddressId getId() {
        return this.id;
    }
    
    public void setId(AdministratorEmailAddressId id) {
        this.id = id;
    }
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    public Administrator getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(Administrator administrator) {
        this.administrator = administrator;
    }
    public Boolean getIsPrimary() {
        return this.isPrimary;
    }
    
    public void setIsPrimary(Boolean isPrimary) {
        this.isPrimary = isPrimary;
    }




}


