package org.greenpole.hibernate.entity;
// Generated 29-May-2015 21:21:44 by Hibernate Tools 4.3.1



/**
 * AdministratorPhoneNumberId generated by hbm2java
 */
public class AdministratorPhoneNumberId  implements java.io.Serializable {


     private int administratorId;
     private String phoneNumber;

    public AdministratorPhoneNumberId() {
    }

    public AdministratorPhoneNumberId(int administratorId, String phoneNumber) {
       this.administratorId = administratorId;
       this.phoneNumber = phoneNumber;
    }
   
    public int getAdministratorId() {
        return this.administratorId;
    }
    
    public void setAdministratorId(int administratorId) {
        this.administratorId = administratorId;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AdministratorPhoneNumberId) ) return false;
		 AdministratorPhoneNumberId castOther = ( AdministratorPhoneNumberId ) other; 
         
		 return (this.getAdministratorId()==castOther.getAdministratorId())
 && ( (this.getPhoneNumber()==castOther.getPhoneNumber()) || ( this.getPhoneNumber()!=null && castOther.getPhoneNumber()!=null && this.getPhoneNumber().equals(castOther.getPhoneNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAdministratorId();
         result = 37 * result + ( getPhoneNumber() == null ? 0 : this.getPhoneNumber().hashCode() );
         return result;
   }   


}


