package org.greenpole.hibernate.entity;
// Generated 29-May-2015 21:21:44 by Hibernate Tools 4.3.1



/**
 * AdministratorPostalAddress generated by hbm2java
 */
public class AdministratorPostalAddress  implements java.io.Serializable {


     private AdministratorPostalAddressId id;
     private Long version;
     private Administrator administrator;
     private String addressLine2;
     private String addressLine3;
     private String addressLine4;
     private String postCode;
     private String city;
     private Boolean isPrimary;

    public AdministratorPostalAddress() {
    }

	
    public AdministratorPostalAddress(AdministratorPostalAddressId id, Administrator administrator) {
        this.id = id;
        this.administrator = administrator;
    }
    public AdministratorPostalAddress(AdministratorPostalAddressId id, Administrator administrator, String addressLine2, String addressLine3, String addressLine4, String postCode, String city, Boolean isPrimary) {
       this.id = id;
       this.administrator = administrator;
       this.addressLine2 = addressLine2;
       this.addressLine3 = addressLine3;
       this.addressLine4 = addressLine4;
       this.postCode = postCode;
       this.city = city;
       this.isPrimary = isPrimary;
    }
   
    public AdministratorPostalAddressId getId() {
        return this.id;
    }
    
    public void setId(AdministratorPostalAddressId id) {
        this.id = id;
    }
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    public Administrator getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(Administrator administrator) {
        this.administrator = administrator;
    }
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    public String getAddressLine3() {
        return this.addressLine3;
    }
    
    public void setAddressLine3(String addressLine3) {
        this.addressLine3 = addressLine3;
    }
    public String getAddressLine4() {
        return this.addressLine4;
    }
    
    public void setAddressLine4(String addressLine4) {
        this.addressLine4 = addressLine4;
    }
    public String getPostCode() {
        return this.postCode;
    }
    
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Boolean getIsPrimary() {
        return this.isPrimary;
    }
    
    public void setIsPrimary(Boolean isPrimary) {
        this.isPrimary = isPrimary;
    }




}


