package org.greenpole.hibernate.entity;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1



/**
 * AdministratorEmailAddress generated by hbm2java
 */
public class AdministratorEmailAddress  implements java.io.Serializable {


     private AdministratorEmailAddressId id;
     private Administrator administrator;

    public AdministratorEmailAddress() {
    }

    public AdministratorEmailAddress(AdministratorEmailAddressId id, Administrator administrator) {
       this.id = id;
       this.administrator = administrator;
    }
   
    public AdministratorEmailAddressId getId() {
        return this.id;
    }
    
    public void setId(AdministratorEmailAddressId id) {
        this.id = id;
    }
    public Administrator getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(Administrator administrator) {
        this.administrator = administrator;
    }




}


