package org.greenpole.hibernate.entity;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1



/**
 * AdministratorResidentialAddress generated by hbm2java
 */
public class AdministratorResidentialAddress  implements java.io.Serializable {


     private AdministratorResidentialAddressId id;
     private Administrator administrator;
     private String type;

    public AdministratorResidentialAddress() {
    }

	
    public AdministratorResidentialAddress(AdministratorResidentialAddressId id, Administrator administrator) {
        this.id = id;
        this.administrator = administrator;
    }
    public AdministratorResidentialAddress(AdministratorResidentialAddressId id, Administrator administrator, String type) {
       this.id = id;
       this.administrator = administrator;
       this.type = type;
    }
   
    public AdministratorResidentialAddressId getId() {
        return this.id;
    }
    
    public void setId(AdministratorResidentialAddressId id) {
        this.id = id;
    }
    public Administrator getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(Administrator administrator) {
        this.administrator = administrator;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


