package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * AdministratorResidentialAddress generated by hbm2java
 */
public class AdministratorResidentialAddress  implements java.io.Serializable {


     private AdministratorResidentialAddressId id;
     private Administrator administrator;
     private String lineType;
     private String addressType;

    public AdministratorResidentialAddress() {
    }

	
    public AdministratorResidentialAddress(AdministratorResidentialAddressId id, Administrator administrator) {
        this.id = id;
        this.administrator = administrator;
    }

    public AdministratorResidentialAddress(AdministratorResidentialAddressId id, Administrator administrator, String lineType, String addressType) {
        this.id = id;
        this.administrator = administrator;
        this.lineType = lineType;
        this.addressType = addressType;
    }
   
    public AdministratorResidentialAddressId getId() {
        return this.id;
    }
    
    public void setId(AdministratorResidentialAddressId id) {
        this.id = id;
    }
    
    public Administrator getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(Administrator administrator) {
        this.administrator = administrator;
    }
    public String getLineType() {
        return this.lineType;
    }
    
    public void setLineType(String lineType) {
        this.lineType = lineType;
    }

    public String getAddressType() {
        return addressType;
    }

    public void setAddressType(String addressType) {
        this.addressType = addressType;
    }


}


