package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * AgentSignature generated by hbm2java
 */
public class AgentSignature  implements java.io.Serializable {


     private int id;
     private StockbrokerAgent stockbrokerAgent;
     private String signaturePath;
     private boolean agentSignaturePrimary;

    public AgentSignature() {
    }

    public AgentSignature(StockbrokerAgent stockbrokerAgent, String signaturePath, boolean agentSignaturePrimary) {
       this.stockbrokerAgent = stockbrokerAgent;
       this.signaturePath = signaturePath;
       this.agentSignaturePrimary = agentSignaturePrimary;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public StockbrokerAgent getStockbrokerAgent() {
        return this.stockbrokerAgent;
    }
    
    public void setStockbrokerAgent(StockbrokerAgent stockbrokerAgent) {
        this.stockbrokerAgent = stockbrokerAgent;
    }
    public String getSignaturePath() {
        return this.signaturePath;
    }
    
    public void setSignaturePath(String signaturePath) {
        this.signaturePath = signaturePath;
    }
    public boolean isAgentSignaturePrimary() {
        return this.agentSignaturePrimary;
    }
    
    public void setAgentSignaturePrimary(boolean agentSignaturePrimary) {
        this.agentSignaturePrimary = agentSignaturePrimary;
    }




}


