package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * AgentSignature generated by hbm2java
 */
public class AgentSignature  implements java.io.Serializable {


     private int id;
     private long versionId;
     private StockbrokerAgent stockbrokerAgent;
     private String title;
     private String signaturePath;
     private boolean agentSignaturePrimary;

    public AgentSignature() {
    }

    public AgentSignature(StockbrokerAgent stockbrokerAgent, String title, String signaturePath, boolean agentSignaturePrimary) {
       this.stockbrokerAgent = stockbrokerAgent;
       this.title = title;
       this.signaturePath = signaturePath;
       this.agentSignaturePrimary = agentSignaturePrimary;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
        /**
     * A getter for AgentSignature object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for AgentSignature object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public StockbrokerAgent getStockbrokerAgent() {
        return this.stockbrokerAgent;
    }
    
    public void setStockbrokerAgent(StockbrokerAgent stockbrokerAgent) {
        this.stockbrokerAgent = stockbrokerAgent;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
    public String getSignaturePath() {
        return this.signaturePath;
    }
    
    public void setSignaturePath(String signaturePath) {
        this.signaturePath = signaturePath;
    }
    public boolean isAgentSignaturePrimary() {
        return this.agentSignaturePrimary;
    }
    
    public void setAgentSignaturePrimary(boolean agentSignaturePrimary) {
        this.agentSignaturePrimary = agentSignaturePrimary;
    }




}


