package org.greenpole.hibernate.entity;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1



/**
 * AprDepartment generated by hbm2java
 */
public class AprDepartment  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;

    public AprDepartment() {
    }

    public AprDepartment(String name, String description) {
       this.name = name;
       this.description = description;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


