package org.greenpole.hibernate.entity;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1



/**
 * AprUnit generated by hbm2java
 */
public class AprUnit  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private int deptId;

    public AprUnit() {
    }

    public AprUnit(String name, String description, int deptId) {
       this.name = name;
       this.description = description;
       this.deptId = deptId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(int deptId) {
        this.deptId = deptId;
    }




}


