package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * Caution generated by hbm2java
 */
public class Caution  implements java.io.Serializable {


     private int id;
     private long versionId;
     private Holder holder;
     private String title;
     private String description;
     private String type;
     private boolean active;
     private Date cautionDate;
     private Date uncautionDate;

    public Caution() {
    }

    public Caution(Holder holder, String title, String description, String type, boolean active, Date cautionDate, Date uncautionDate) {
       this.holder = holder;
       this.title = title;
       this.description = description;
       this.type = type;
       this.active = active;
       this.cautionDate = cautionDate;
       this.uncautionDate = uncautionDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Holder getHolder() {
        return this.holder;
    }
    
    /**
     * A getter for Caution object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for Caution object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public void setHolder(Holder holder) {
        this.holder = holder;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    public Date getCautionDate() {
        return cautionDate;
    }

    public void setCautionDate(Date cautionDate) {
        this.cautionDate = cautionDate;
    }

    public Date getUncautionDate() {
        return uncautionDate;
    }

    public void setUncautionDate(Date uncautionDate) {
        this.uncautionDate = uncautionDate;
    }




}


