package org.greenpole.hibernate.entity;
// Generated 25-Jun-2015 15:41:35 by Hibernate Tools 4.3.1



/**
 * CertificateTransfer generated by hbm2java
 */
public class CertificateTransfer  implements java.io.Serializable {


     private int id;
     private Long version;
     private Certificate certificate;
     private Holder holder;
     private String fromTo;

    public CertificateTransfer() {
    }

    public CertificateTransfer(Certificate certificate, Holder holder, String fromTo) {
       this.certificate = certificate;
       this.holder = holder;
       this.fromTo = fromTo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    public Certificate getCertificate() {
        return this.certificate;
    }
    
    public void setCertificate(Certificate certificate) {
        this.certificate = certificate;
    }
    public Holder getHolder() {
        return this.holder;
    }
    
    public void setHolder(Holder holder) {
        this.holder = holder;
    }
    public String getFromTo() {
        return this.fromTo;
    }
    
    public void setFromTo(String fromTo) {
        this.fromTo = fromTo;
    }




}


