package org.greenpole.hibernate.entity;
// Generated 22-Jun-2015 15:17:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CertificateEvent generated by hbm2java
 */
public class CertificateEvent  implements java.io.Serializable {


     private int id;
     private Long version;
     private Boolean splitStatus;
     private Boolean mergeStatus;
     private Date eventDate;
     private Integer certId;

    public CertificateEvent() {
    }

    public CertificateEvent(Boolean splitStatus, Boolean mergeStatus, Date eventDate, Integer certId) {
       this.splitStatus = splitStatus;
       this.mergeStatus = mergeStatus;
       this.eventDate = eventDate;
       this.certId = certId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    public Boolean getSplitStatus() {
        return this.splitStatus;
    }
    
    public void setSplitStatus(Boolean splitStatus) {
        this.splitStatus = splitStatus;
    }
    public Boolean getMergeStatus() {
        return this.mergeStatus;
    }
    
    public void setMergeStatus(Boolean mergeStatus) {
        this.mergeStatus = mergeStatus;
    }
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }
    public Integer getCertId() {
        return this.certId;
    }
    
    public void setCertId(Integer certId) {
        this.certId = certId;
    }




}


