package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClientCompany generated by hbm2java
 */
public class ClientCompany  implements java.io.Serializable {

     private int id;            //primary id
     private long versionId;    //version
     private ClientCompany clientCompany;   
     private Depository depository;     
     private String name;
     private String code;
     private String nseSector;
     private String ceo;
     private String secretary;
     private String address;
     private String depository_1;
     private boolean valid;
     private boolean merged;
     private boolean clientCompanyPrimary;
     private Set clientCompanies = new HashSet(0);
     private Set initialPublicOffers = new HashSet(0);
     private Set shareBonuses = new HashSet(0);
     private Set gms = new HashSet(0);
     private Set certificates = new HashSet(0);
     private Set dividends = new HashSet(0);
     private Set holderCompanyAccounts = new HashSet(0);
     private Set reconstructions = new HashSet(0);
     private Set clientCompanyPhoneNumbers = new HashSet(0);
     private Set clientCompanyEmailAddresses = new HashSet(0);
     private Set privatePlacements = new HashSet(0);
     private Set shareQuotations = new HashSet(0);
     private Set dividendDeclareds = new HashSet(0);
     private Set processedTransactions = new HashSet(0);
     private Set rightsIssues = new HashSet(0);
     private Set suspendedTransactions = new HashSet(0);
     private Set bondOffers = new HashSet(0);

    public ClientCompany() {
    }

    public ClientCompany(Depository depository, String name, String code, String ceo, String address) {
        this.depository = depository;
        this.name = name;        
        this.code = code;
        this.ceo = ceo;
        this.address = address;
    }
    
    
    
    public ClientCompany(ClientCompany clientCompany, Depository depository, String name, String code, String nseSector, String ceo, String secretary, String address, String depository_1, boolean valid, boolean merged, boolean clientCompanyPrimary, Set clientCompanies, Set initialPublicOffers, Set shareBonuses, Set gms, Set certificates, Set dividends, Set holderCompanyAccounts, Set reconstructions, Set clientCompanyPhoneNumbers, Set clientCompanyEmailAddresses, Set privatePlacements, Set shareQuotations, Set dividendDeclareds, Set processedTransactions, Set rightsIssues, Set suspendedTransactions, Set bondOffers) {
       this.clientCompany = clientCompany;
       this.depository = depository;
       this.name = name;
       this.code = code;
       this.nseSector = nseSector;
       this.ceo = ceo;
       this.secretary = secretary;
       this.address = address;
       this.depository_1 = depository_1;
       this.valid = valid;
       this.merged = merged;
       this.clientCompanyPrimary = clientCompanyPrimary;
       this.clientCompanies = clientCompanies;
       this.initialPublicOffers = initialPublicOffers;
       this.shareBonuses = shareBonuses;
       this.gms = gms;
       this.certificates = certificates;
       this.dividends = dividends;
       this.holderCompanyAccounts = holderCompanyAccounts;
       this.reconstructions = reconstructions;
       this.clientCompanyPhoneNumbers = clientCompanyPhoneNumbers;
       this.clientCompanyEmailAddresses = clientCompanyEmailAddresses;
       this.privatePlacements = privatePlacements;
       this.shareQuotations = shareQuotations;
       this.dividendDeclareds = dividendDeclareds;
       this.processedTransactions = processedTransactions;
       this.rightsIssues = rightsIssues;
       this.suspendedTransactions = suspendedTransactions;
       this.bondOffers = bondOffers;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    /**
     * A getter for ClientCompany object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for ClientCompany object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public ClientCompany getClientCompany() {
        return this.clientCompany;
    }
    
    public void setClientCompany(ClientCompany clientCompany) {
        this.clientCompany = clientCompany;
    }
    public Depository getDepository() {
        return this.depository;
    }
    
    public void setDepository(Depository depository) {
        this.depository = depository;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getNseSector() {
        return this.nseSector;
    }
    
    public void setNseSector(String nseSector) {
        this.nseSector = nseSector;
    }
    public String getCeo() {
        return this.ceo;
    }
    
    public void setCeo(String ceo) {
        this.ceo = ceo;
    }
    public String getSecretary() {
        return this.secretary;
    }
    
    public void setSecretary(String secretary) {
        this.secretary = secretary;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getDepository_1() {
        return this.depository_1;
    }
    
    public void setDepository_1(String depository_1) {
        this.depository_1 = depository_1;
    }
    public boolean isValid() {
        return this.valid;
    }
    
    public void setValid(boolean valid) {
        this.valid = valid;
    }
    public boolean isMerged() {
        return this.merged;
    }
    
    public void setMerged(boolean merged) {
        this.merged = merged;
    }
    public boolean isClientCompanyPrimary() {
        return this.clientCompanyPrimary;
    }
    
    public void setClientCompanyPrimary(boolean clientCompanyPrimary) {
        this.clientCompanyPrimary = clientCompanyPrimary;
    }
    public Set getClientCompanies() {
        return this.clientCompanies;
    }
    
    public void setClientCompanies(Set clientCompanies) {
        this.clientCompanies = clientCompanies;
    }
    public Set getInitialPublicOffers() {
        return this.initialPublicOffers;
    }
    
    public void setInitialPublicOffers(Set initialPublicOffers) {
        this.initialPublicOffers = initialPublicOffers;
    }
    public Set getShareBonuses() {
        return this.shareBonuses;
    }
    
    public void setShareBonuses(Set shareBonuses) {
        this.shareBonuses = shareBonuses;
    }
    public Set getGms() {
        return this.gms;
    }
    
    public void setGms(Set gms) {
        this.gms = gms;
    }
    public Set getCertificates() {
        return this.certificates;
    }
    
    public void setCertificates(Set certificates) {
        this.certificates = certificates;
    }
    public Set getDividends() {
        return this.dividends;
    }
    
    public void setDividends(Set dividends) {
        this.dividends = dividends;
    }
    public Set getHolderCompanyAccounts() {
        return this.holderCompanyAccounts;
    }
    
    public void setHolderCompanyAccounts(Set holderCompanyAccounts) {
        this.holderCompanyAccounts = holderCompanyAccounts;
    }
    public Set getReconstructions() {
        return this.reconstructions;
    }
    
    public void setReconstructions(Set reconstructions) {
        this.reconstructions = reconstructions;
    }
    public Set getClientCompanyPhoneNumbers() {
        return this.clientCompanyPhoneNumbers;
    }
    
    public void setClientCompanyPhoneNumbers(Set clientCompanyPhoneNumbers) {
        this.clientCompanyPhoneNumbers = clientCompanyPhoneNumbers;
    }
    public Set getClientCompanyEmailAddresses() {
        return this.clientCompanyEmailAddresses;
    }
    
    public void setClientCompanyEmailAddresses(Set clientCompanyEmailAddresses) {
        this.clientCompanyEmailAddresses = clientCompanyEmailAddresses;
    }
    public Set getPrivatePlacements() {
        return this.privatePlacements;
    }
    
    public void setPrivatePlacements(Set privatePlacements) {
        this.privatePlacements = privatePlacements;
    }
    public Set getShareQuotations() {
        return this.shareQuotations;
    }
    
    public void setShareQuotations(Set shareQuotations) {
        this.shareQuotations = shareQuotations;
    }
    public Set getDividendDeclareds() {
        return this.dividendDeclareds;
    }
    
    public void setDividendDeclareds(Set dividendDeclareds) {
        this.dividendDeclareds = dividendDeclareds;
    }
    public Set getProcessedTransactions() {
        return this.processedTransactions;
    }
    
    public void setProcessedTransactions(Set processedTransactions) {
        this.processedTransactions = processedTransactions;
    }
    public Set getRightsIssues() {
        return this.rightsIssues;
    }
    
    public void setRightsIssues(Set rightsIssues) {
        this.rightsIssues = rightsIssues;
    }
    public Set getSuspendedTransactions() {
        return this.suspendedTransactions;
    }
    
    public void setSuspendedTransactions(Set suspendedTransactions) {
        this.suspendedTransactions = suspendedTransactions;
    }
    public Set getBondOffers() {
        return this.bondOffers;
    }
    
    public void setBondOffers(Set bondOffers) {
        this.bondOffers = bondOffers;
    }




}


