package org.greenpole.hibernate.entity;
// Generated 29-May-2015 21:21:44 by Hibernate Tools 4.3.1



/**
 * ClientCompanyEmailAddress generated by hbm2java
 */
public class ClientCompanyEmailAddress  implements java.io.Serializable {


     private ClientCompanyEmailAddressId id;
     private Long version;
     private ClientCompany clientCompany;
     private Boolean isPrimary;

    public ClientCompanyEmailAddress() {
    }

	
    public ClientCompanyEmailAddress(ClientCompanyEmailAddressId id, ClientCompany clientCompany) {
        this.id = id;
        this.clientCompany = clientCompany;
    }
    public ClientCompanyEmailAddress(ClientCompanyEmailAddressId id, ClientCompany clientCompany, Boolean isPrimary) {
       this.id = id;
       this.clientCompany = clientCompany;
       this.isPrimary = isPrimary;
    }
   
    public ClientCompanyEmailAddressId getId() {
        return this.id;
    }
    
    public void setId(ClientCompanyEmailAddressId id) {
        this.id = id;
    }
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    public ClientCompany getClientCompany() {
        return this.clientCompany;
    }
    
    public void setClientCompany(ClientCompany clientCompany) {
        this.clientCompany = clientCompany;
    }
    public Boolean getIsPrimary() {
        return this.isPrimary;
    }
    
    public void setIsPrimary(Boolean isPrimary) {
        this.isPrimary = isPrimary;
    }




}


