package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * ClientCompanyPhoneNumberId generated by hbm2java
 */
public class ClientCompanyPhoneNumberId  implements java.io.Serializable {


     private int clientCompanyId;
     private String phoneNumber;

    public ClientCompanyPhoneNumberId() {
    }

    public ClientCompanyPhoneNumberId(int clientCompanyId, String phoneNumber) {
       this.clientCompanyId = clientCompanyId;
       this.phoneNumber = phoneNumber;
    }
   
    public int getClientCompanyId() {
        return this.clientCompanyId;
    }
    
    public void setClientCompanyId(int clientCompanyId) {
        this.clientCompanyId = clientCompanyId;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClientCompanyPhoneNumberId) ) return false;
		 ClientCompanyPhoneNumberId castOther = ( ClientCompanyPhoneNumberId ) other; 
         
		 return (this.getClientCompanyId()==castOther.getClientCompanyId())
 && ( (this.getPhoneNumber()==castOther.getPhoneNumber()) || ( this.getPhoneNumber()!=null && castOther.getPhoneNumber()!=null && this.getPhoneNumber().equals(castOther.getPhoneNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getClientCompanyId();
         result = 37 * result + ( getPhoneNumber() == null ? 0 : this.getPhoneNumber().hashCode() );
         return result;
   }   


}


