package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * ClientCompanyEmailAddress generated by hbm2java
 */
public class ClientCompanyEmailAddress  implements java.io.Serializable {


     private ClientCompanyEmailAddressId id;
     private ClientCompany clientCompany;

    public ClientCompanyEmailAddress() {
    }

    public ClientCompanyEmailAddress(ClientCompanyEmailAddressId id, ClientCompany clientCompany) {
       this.id = id;
       this.clientCompany = clientCompany;
    }
   
    public ClientCompanyEmailAddressId getId() {
        return this.id;
    }
    
    public void setId(ClientCompanyEmailAddressId id) {
        this.id = id;
    }
    public ClientCompany getClientCompany() {
        return this.clientCompany;
    }
    
    public void setClientCompany(ClientCompany clientCompany) {
        this.clientCompany = clientCompany;
    }




}


