package org.greenpole.hibernate.entity;
// Generated 24-Jun-2015 14:34:48 by Hibernate Tools 4.3.1



/**
 * DigitalCapture generated by hbm2java
 */
public class DigitalCapture  implements java.io.Serializable {


     private int id;
     private Long version;
     private Holder holder;
     private String title;
     private byte[] signature;
     private byte[] fingerprint;

    public DigitalCapture() {
    }

    public DigitalCapture(Holder holder, String title, byte[] signature, byte[] fingerprint) {
       this.holder = holder;
       this.title = title;
       this.signature = signature;
       this.fingerprint = fingerprint;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    public Holder getHolder() {
        return this.holder;
    }
    
    public void setHolder(Holder holder) {
        this.holder = holder;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public byte[] getSignature() {
        return this.signature;
    }
    
    public void setSignature(byte[] signature) {
        this.signature = signature;
    }
    public byte[] getFingerprint() {
        return this.fingerprint;
    }
    
    public void setFingerprint(byte[] fingerprint) {
        this.fingerprint = fingerprint;
    }




}


