package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * HolderVotingId generated by hbm2java
 */
public class HolderVotingId  implements java.io.Serializable {


     private int holderId;
     private long versionId;
     private int votingProcessId;

    public HolderVotingId() {
    }

    public HolderVotingId(int holderId, int votingProcessId) {
       this.holderId = holderId;
       this.votingProcessId = votingProcessId;
    }
   
    public int getHolderId() {
        return this.holderId;
    }
    
    public void setHolderId(int holderId) {
        this.holderId = holderId;
    }
    /**
     * A getter for HolderVotingId object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for HolderVotingId object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public int getVotingProcessId() {
        return this.votingProcessId;
    }
    
    public void setVotingProcessId(int votingProcessId) {
        this.votingProcessId = votingProcessId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HolderVotingId) ) return false;
		 HolderVotingId castOther = ( HolderVotingId ) other; 
         
		 return (this.getHolderId()==castOther.getHolderId())
 && (this.getVotingProcessId()==castOther.getVotingProcessId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getHolderId();
         result = 37 * result + this.getVotingProcessId();
         return result;
   }   


}


