package org.greenpole.hibernate.entity;
// Generated 26-Apr-2015 06:13:16 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HolderChanges generated by hbm2java
 */
public class HolderChanges  implements java.io.Serializable {


     private int id;
     private long versionId;
     private String initialForm;
     private String currentForm;
     private HolderChangeType holderChangeType;
     private Date changeDate;
     private Holder holder;

    public HolderChanges() {
    }

    public HolderChanges(String initialForm, String currentForm, HolderChangeType holderChangeType, Date changeDate, Holder holder) {
       this.initialForm = initialForm;
       this.currentForm = currentForm;
       this.holderChangeType = holderChangeType;
       this.changeDate = changeDate;
       this.holder = holder;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    /**
     * A getter for Administrator object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for Administrator object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public String getInitialForm() {
        return this.initialForm;
    }
    
    public void setInitialForm(String initialForm) {
        this.initialForm = initialForm;
    }
    public String getCurrentForm() {
        return this.currentForm;
    }
    
    public void setCurrentForm(String currentForm) {
        this.currentForm = currentForm;
    }
    public HolderChangeType getHolderChangeType() {
        return this.holderChangeType;
    }
    
    public void setHolderChangeType(HolderChangeType holderChangeType) {
        this.holderChangeType = holderChangeType;
    }
    public Date getChangeDate() {
        return this.changeDate;
    }
    
    public void setChangeDate(Date changeDate) {
        this.changeDate = changeDate;
    }

    public Holder getHolder() {
        return holder;
    }

    public void setHolder(Holder holder) {
        this.holder = holder;
    }

}


