package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * HolderResidentialAddress generated by hbm2java
 */
public class HolderResidentialAddress  implements java.io.Serializable {


     private HolderResidentialAddressId id;
     private Holder holder;
     private String lineType;
     private String addressType;

    public HolderResidentialAddress() {
    }

	
    public HolderResidentialAddress(HolderResidentialAddressId id, Holder holder) {
        this.id = id;
        this.holder = holder;
    }

    public HolderResidentialAddress(HolderResidentialAddressId id, Holder holder, String lineType, String addressType) {
        this.id = id;
        this.holder = holder;
        this.lineType = lineType;
        this.addressType = addressType;
    }
   
    public HolderResidentialAddressId getId() {
        return this.id;
    }
    
    public void setId(HolderResidentialAddressId id) {
        this.id = id;
    }
    
    public Holder getHolder() {
        return this.holder;
    }
    
    public void setHolder(Holder holder) {
        this.holder = holder;
    }
    public String getLineType() {
        return this.lineType;
    }
    
    public void setLineType(String lineType) {
        this.lineType = lineType;
    }

    public String getAddressType() {
        return addressType;
    }

    public void setAddressType(String addressType) {
        this.addressType = addressType;
    }


}


