package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * HolderPhoneNumberId generated by hbm2java
 */
public class HolderPhoneNumberId  implements java.io.Serializable {


     private int holderId;
     private String phoneNumber;

    public HolderPhoneNumberId() {
    }

    public HolderPhoneNumberId(int holderId, String phoneNumber) {
       this.holderId = holderId;
       this.phoneNumber = phoneNumber;
    }
   
    public int getHolderId() {
        return this.holderId;
    }
    
    public void setHolderId(int holderId) {
        this.holderId = holderId;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HolderPhoneNumberId) ) return false;
		 HolderPhoneNumberId castOther = ( HolderPhoneNumberId ) other; 
         
		 return (this.getHolderId()==castOther.getHolderId())
 && ( (this.getPhoneNumber()==castOther.getPhoneNumber()) || ( this.getPhoneNumber()!=null && castOther.getPhoneNumber()!=null && this.getPhoneNumber().equals(castOther.getPhoneNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getHolderId();
         result = 37 * result + ( getPhoneNumber() == null ? 0 : this.getPhoneNumber().hashCode() );
         return result;
   }   


}


