package org.greenpole.hibernate.entity;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1

import org.greenpole.hibernate.backup_entity.*;
import org.greenpole.hibernate.entity.*;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1



/**
 * HolderPhoneNumberId generated by hbm2java
 */
public class HolderPhoneNumberId  implements java.io.Serializable {


     private int holderId;
     private String phoneNumber;
     private int lineNumber;

    public HolderPhoneNumberId() {
    }

    public HolderPhoneNumberId(int holderId, String phoneNumber, int lineNumber) {
       this.holderId = holderId;
       this.phoneNumber = phoneNumber;
       this.lineNumber = lineNumber;
    }
   
    public int getHolderId() {
        return this.holderId;
    }
    
    public void setHolderId(int holderId) {
        this.holderId = holderId;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public int getLineNumber() {
        return this.lineNumber;
    }
    
    public void setLineNumber(int lineNumber) {
        this.lineNumber = lineNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HolderPhoneNumberId) ) return false;
		 HolderPhoneNumberId castOther = ( HolderPhoneNumberId ) other; 
         
		 return (this.getHolderId()==castOther.getHolderId())
 && ( (this.getPhoneNumber()==castOther.getPhoneNumber()) || ( this.getPhoneNumber()!=null && castOther.getPhoneNumber()!=null && this.getPhoneNumber().equals(castOther.getPhoneNumber()) ) )
 && (this.getLineNumber()==castOther.getLineNumber());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getHolderId();
         result = 37 * result + ( getPhoneNumber() == null ? 0 : this.getPhoneNumber().hashCode() );
         result = 37 * result + this.getLineNumber();
         return result;
   }   


}


