package org.greenpole.hibernate.entity;
// Generated 16-May-2015 16:13:37 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * HolderType generated by hbm2java
 */
public class HolderType  implements java.io.Serializable {


     private int id;
     private long versionId;
     private String type;
     private String description;
     private Set holders = new HashSet(0);

    public HolderType() {
    }

    public HolderType(String type, String description, Set holders) {
       this.type = type;
       this.description = description;
       this.holders = holders;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    /**
     * A getter for Administrator object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for Administrator object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getHolders() {
        return this.holders;
    }
    
    public void setHolders(Set holders) {
        this.holders = holders;
    }




}


