package org.greenpole.hibernate.entity;
// Generated 27-Apr-2015 15:19:42 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * HolderChangeType generated by hbm2java
 */
public class HolderChangeType  implements java.io.Serializable {


     private int id;
     private long versionId;
     private String changeType;
     private String description;
     private Set holderChanges = new HashSet(0);

    public HolderChangeType() {
    }

    public HolderChangeType(String changeType, String description, Set holderChanges) {
       this.changeType = changeType;
       this.description = description;
       this.holderChanges = holderChanges;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    /**
     * A getter for Administrator object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for Administrator object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public String getChangeType() {
        return this.changeType;
    }
    
    public void setChangeType(String changeType) {
        this.changeType = changeType;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getHolderChanges() {
        return holderChanges;
    }

    public void setHolderChanges(Set holderChanges) {
        this.holderChanges = holderChanges;
    }




}


