package org.greenpole.hibernate.entity;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1



/**
 * HolderResidentialAddress generated by hbm2java
 */
public class HolderResidentialAddress  implements java.io.Serializable {


     private HolderResidentialAddressId id;
     private Holder holder;
     private String type;

    public HolderResidentialAddress() {
    }

	
    public HolderResidentialAddress(HolderResidentialAddressId id, Holder holder) {
        this.id = id;
        this.holder = holder;
    }
    public HolderResidentialAddress(HolderResidentialAddressId id, Holder holder, String type) {
       this.id = id;
       this.holder = holder;
       this.type = type;
    }
   
    public HolderResidentialAddressId getId() {
        return this.id;
    }
    
    public void setId(HolderResidentialAddressId id) {
        this.id = id;
    }
    public Holder getHolder() {
        return this.holder;
    }
    
    public void setHolder(Holder holder) {
        this.holder = holder;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


