package org.greenpole.hibernate.entity;
// Generated 25-Jun-2015 15:58:53 by Hibernate Tools 4.3.1



/**
 * HolderPhoneNumber generated by hbm2java
 */
public class HolderPhoneNumber  implements java.io.Serializable {


     private int id;
     private Long version;
     private Holder holder;
     private String phoneNumber;
     private Boolean isPrimary;

    public HolderPhoneNumber() {
    }

    public HolderPhoneNumber(Holder holder, String phoneNumber, Boolean isPrimary) {
       this.holder = holder;
       this.phoneNumber = phoneNumber;
       this.isPrimary = isPrimary;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    public Holder getHolder() {
        return this.holder;
    }
    
    public void setHolder(Holder holder) {
        this.holder = holder;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Boolean getIsPrimary() {
        return this.isPrimary;
    }
    
    public void setIsPrimary(Boolean isPrimary) {
        this.isPrimary = isPrimary;
    }




}


