package org.greenpole.hibernate.entity;
// Generated 23-Jun-2015 04:56:55 by Hibernate Tools 4.3.1



/**
 * HolderBonusId generated by hbm2java
 */
public class HolderBonusId  implements java.io.Serializable {


     private int holderId;
     private int shareBonusId;

    public HolderBonusId() {
    }

    public HolderBonusId(int holderId, int shareBonusId) {
       this.holderId = holderId;
       this.shareBonusId = shareBonusId;
    }
   
    public int getHolderId() {
        return this.holderId;
    }
    
    public void setHolderId(int holderId) {
        this.holderId = holderId;
    }
    public int getShareBonusId() {
        return this.shareBonusId;
    }
    
    public void setShareBonusId(int shareBonusId) {
        this.shareBonusId = shareBonusId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HolderBonusId) ) return false;
		 HolderBonusId castOther = ( HolderBonusId ) other; 
         
		 return (this.getHolderId()==castOther.getHolderId())
 && (this.getShareBonusId()==castOther.getShareBonusId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getHolderId();
         result = 37 * result + this.getShareBonusId();
         return result;
   }   


}


