package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * HolderEmailAddressId generated by hbm2java
 */
public class HolderEmailAddressId  implements java.io.Serializable {


     private int holderId;
     private String emailAddress;

    public HolderEmailAddressId() {
    }

    public HolderEmailAddressId(int holderId, String emailAddress) {
       this.holderId = holderId;
       this.emailAddress = emailAddress;
    }
   
    public int getHolderId() {
        return this.holderId;
    }
    
    public void setHolderId(int holderId) {
        this.holderId = holderId;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HolderEmailAddressId) ) return false;
		 HolderEmailAddressId castOther = ( HolderEmailAddressId ) other; 
         
		 return (this.getHolderId()==castOther.getHolderId())
 && ( (this.getEmailAddress()==castOther.getEmailAddress()) || ( this.getEmailAddress()!=null && castOther.getEmailAddress()!=null && this.getEmailAddress().equals(castOther.getEmailAddress()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getHolderId();
         result = 37 * result + ( getEmailAddress() == null ? 0 : this.getEmailAddress().hashCode() );
         return result;
   }   


}


