package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 8:58:08 AM by Hibernate Tools 4.3.1

import org.greenpole.hibernate.backup_entity.*;
import org.greenpole.hibernate.entity.*;
// Generated Apr 2, 2015 8:58:08 AM by Hibernate Tools 4.3.1



/**
 * Notification generated by hbm2java
 */
public class Notification  implements java.io.Serializable {


     private int id;
     private long versionId;
     private String fileName;
     private String description;
     private String sentFrom;
     private String sentTo;
     private String fromType;
     private String toType;
     private boolean attendedTo;

    public Notification() {
    }

    public Notification(String fileName, String description, String sentFrom, String sentTo, String fromType, String toType, boolean attendedTo) {
       this.fileName = fileName;
       this.description = description;
       this.sentFrom = sentFrom;
       this.sentTo = sentTo;
       this.fromType = fromType;
       this.toType = toType;
       this.attendedTo = attendedTo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    /**
     * A getter for IpoApplication object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for IpoApplication object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getSentFrom() {
        return this.sentFrom;
    }
    
    public void setSentFrom(String sentFrom) {
        this.sentFrom = sentFrom;
    }
    public String getSentTo() {
        return this.sentTo;
    }
    
    public void setSentTo(String sentTo) {
        this.sentTo = sentTo;
    }
    public String getFromType() {
        return this.fromType;
    }
    
    public void setFromType(String fromType) {
        this.fromType = fromType;
    }
    public String getToType() {
        return this.toType;
    }
    
    public void setToType(String toType) {
        this.toType = toType;
    }
    public boolean isAttendedTo() {
        return this.attendedTo;
    }
    
    public void setAttendedTo(boolean attendedTo) {
        this.attendedTo = attendedTo;
    }




}


