package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * PrivatePlacementApplication generated by hbm2java
 */
public class PrivatePlacementApplication  implements java.io.Serializable {


     private int id;
     private long versionId;
     private ClearingHouse clearingHouse;
     private Holder holder;
     private PrivatePlacement privatePlacement;
     private String issuer;
     private int sharesSubscribed;
     private Double amountPaid;
     private String issuingHouse;
     private Double sharesSubscribedValue;
     private int sharesAdjusted;
     private Double returnMoney;
     private boolean processingPayment;
     private boolean approved;
     private boolean canceled;

    public PrivatePlacementApplication() {
    }

    public PrivatePlacementApplication(ClearingHouse clearingHouse, Holder holder, PrivatePlacement privatePlacement, String issuer, int sharesSubscribed, Double amountPaid, String issuingHouse, Double sharesSubscribedValue, int sharesAdjusted, Double returnMoney, boolean processingPayment, boolean approved, boolean canceled) {
       this.clearingHouse = clearingHouse;
       this.holder = holder;
       this.privatePlacement = privatePlacement;
       this.issuer = issuer;
       this.sharesSubscribed = sharesSubscribed;
       this.amountPaid = amountPaid;
       this.issuingHouse = issuingHouse;
       this.sharesSubscribedValue = sharesSubscribedValue;
       this.sharesAdjusted = sharesAdjusted;
       this.returnMoney = returnMoney;
       this.processingPayment = processingPayment;
       this.approved = approved;
       this.canceled = canceled;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    /**
     * A getter for PrivatePlacementApplication object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for PrivatePlacementApplication object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public ClearingHouse getClearingHouse() {
        return this.clearingHouse;
    }
    
    public void setClearingHouse(ClearingHouse clearingHouse) {
        this.clearingHouse = clearingHouse;
    }
    public Holder getHolder() {
        return this.holder;
    }
    
    public void setHolder(Holder holder) {
        this.holder = holder;
    }
    public PrivatePlacement getPrivatePlacement() {
        return this.privatePlacement;
    }
    
    public void setPrivatePlacement(PrivatePlacement privatePlacement) {
        this.privatePlacement = privatePlacement;
    }
    public String getIssuer() {
        return this.issuer;
    }
    
    public void setIssuer(String issuer) {
        this.issuer = issuer;
    }
    public int getSharesSubscribed() {
        return this.sharesSubscribed;
    }
    
    public void setSharesSubscribed(int sharesSubscribed) {
        this.sharesSubscribed = sharesSubscribed;
    }
    public Double getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(Double amountPaid) {
        this.amountPaid = amountPaid;
    }
    public String getIssuingHouse() {
        return this.issuingHouse;
    }
    
    public void setIssuingHouse(String issuingHouse) {
        this.issuingHouse = issuingHouse;
    }
    public Double getSharesSubscribedValue() {
        return this.sharesSubscribedValue;
    }
    
    public void setSharesSubscribedValue(Double sharesSubscribedValue) {
        this.sharesSubscribedValue = sharesSubscribedValue;
    }

    public int getSharesAdjusted() {
        return sharesAdjusted;
    }

    public void setSharesAdjusted(int sharesAdjusted) {
        this.sharesAdjusted = sharesAdjusted;
    }
    public Double getReturnMoney() {
        return this.returnMoney;
    }
    
    public void setReturnMoney(Double returnMoney) {
        this.returnMoney = returnMoney;
    }

    public boolean isProcessingPayment() {
        return processingPayment;
    }

    public void setProcessingPayment(boolean processingPayment) {
        this.processingPayment = processingPayment;
    }

    public boolean isApproved() {
        return approved;
    }

    public void setApproved(boolean approved) {
        this.approved = approved;
    }
    public boolean isCanceled() {
        return this.canceled;
    }
    
    public void setCanceled(boolean canceled) {
        this.canceled = canceled;
    }




}


