package org.greenpole.hibernate.entity;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProcessedTransaction generated by hbm2java
 */
public class ProcessedTransaction  implements java.io.Serializable {


     private int id;
     private ClientCompany clientCompany;
     private int cscsTransactionId;
     private String companyName;
     private Set processedTransactionHolders = new HashSet(0);

    public ProcessedTransaction() {
    }

    public ProcessedTransaction(ClientCompany clientCompany, int cscsTransactionId, String companyName, Set processedTransactionHolders) {
       this.clientCompany = clientCompany;
       this.cscsTransactionId = cscsTransactionId;
       this.companyName = companyName;
       this.processedTransactionHolders = processedTransactionHolders;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ClientCompany getClientCompany() {
        return this.clientCompany;
    }
    
    public void setClientCompany(ClientCompany clientCompany) {
        this.clientCompany = clientCompany;
    }
    public int getCscsTransactionId() {
        return this.cscsTransactionId;
    }
    
    public void setCscsTransactionId(int cscsTransactionId) {
        this.cscsTransactionId = cscsTransactionId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public Set getProcessedTransactionHolders() {
        return this.processedTransactionHolders;
    }
    
    public void setProcessedTransactionHolders(Set processedTransactionHolders) {
        this.processedTransactionHolders = processedTransactionHolders;
    }




}


