package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProcessedTransaction generated by hbm2java
 */
public class ProcessedTransaction  implements java.io.Serializable {


     private int id;
     private long versionId;
     private ClientCompany clientCompany;
     private int cscsTransactionId;
     private String companyName;
     private TransactionType transactionType;
     private Set processedTransactionHolders = new HashSet(0);

    public ProcessedTransaction() {
    }

    public ProcessedTransaction(ClientCompany clientCompany, int cscsTransactionId, String companyName, TransactionType transactionType, Set processedTransactionHolders) {
       this.clientCompany = clientCompany;
       this.cscsTransactionId = cscsTransactionId;
       this.companyName = companyName;
       this.processedTransactionHolders = processedTransactionHolders;
       this.transactionType = transactionType;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    /**
     * A getter for ProcessedTransaction object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for ProcessedTransaction object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public ClientCompany getClientCompany() {
        return this.clientCompany;
    }
    
    public void setClientCompany(ClientCompany clientCompany) {
        this.clientCompany = clientCompany;
    }
    public int getCscsTransactionId() {
        return this.cscsTransactionId;
    }
    
    public void setCscsTransactionId(int cscsTransactionId) {
        this.cscsTransactionId = cscsTransactionId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public TransactionType getTransactionType() {
        return transactionType;
    }

    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }
    public Set getProcessedTransactionHolders() {
        return this.processedTransactionHolders;
    }
    
    public void setProcessedTransactionHolders(Set processedTransactionHolders) {
        this.processedTransactionHolders = processedTransactionHolders;
    }




}


