package org.greenpole.hibernate.entity;
// Generated 15-Jun-2015 13:01:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ReconstructionType generated by hbm2java
 */
public class ReconstructionType  implements java.io.Serializable {


     private int id;
     private Long version;
     private String type;
     private String description;
     private Set reconstructions = new HashSet(0);

    public ReconstructionType() {
    }

    public ReconstructionType(String type, String description, Set reconstructions) {
       this.type = type;
       this.description = description;
       this.reconstructions = reconstructions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getReconstructions() {
        return this.reconstructions;
    }
    
    public void setReconstructions(Set reconstructions) {
        this.reconstructions = reconstructions;
    }




}


