package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ShareBonus generated by hbm2java
 */
public class ShareBonus  implements java.io.Serializable {


     private int id;
     private long versionId;
     private ClientCompany clientCompany;
     private String title;
     private Date qualifyDate;
     private int qualifyShareUnit;
     private int bonusUnitPerQualifyUnit;
     private Set certificates = new HashSet(0);

    public ShareBonus() {
    }

    public ShareBonus(ClientCompany clientCompany, String title, Date qualifyDate, int qualifyShareUnit, int bonusUnitPerQualifyUnit, Set certificates) {
       this.clientCompany = clientCompany;
       this.title = title;
       this.qualifyDate = qualifyDate;
       this.qualifyShareUnit = qualifyShareUnit;
       this.bonusUnitPerQualifyUnit = bonusUnitPerQualifyUnit;
       this.certificates = certificates;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
     /**
     * A getter for ShareBonus object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for ShareBonus object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public ClientCompany getClientCompany() {
        return this.clientCompany;
    }
    
    public void setClientCompany(ClientCompany clientCompany) {
        this.clientCompany = clientCompany;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getQualifyDate() {
        return this.qualifyDate;
    }
    
    public void setQualifyDate(Date qualifyDate) {
        this.qualifyDate = qualifyDate;
    }
    public int getQualifyShareUnit() {
        return this.qualifyShareUnit;
    }
    
    public void setQualifyShareUnit(int qualifyShareUnit) {
        this.qualifyShareUnit = qualifyShareUnit;
    }
    public int getBonusUnitPerQualifyUnit() {
        return this.bonusUnitPerQualifyUnit;
    }
    
    public void setBonusUnitPerQualifyUnit(int bonusUnitPerQualifyUnit) {
        this.bonusUnitPerQualifyUnit = bonusUnitPerQualifyUnit;
    }
    public Set getCertificates() {
        return this.certificates;
    }
    
    public void setCertificates(Set certificates) {
        this.certificates = certificates;
    }




}


