package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * StockbrokerEmailAddress generated by hbm2java
 */
public class StockbrokerEmailAddress  implements java.io.Serializable {


     private StockbrokerEmailAddressId id;
     private Stockbroker stockbroker;

    public StockbrokerEmailAddress() {
    }

    public StockbrokerEmailAddress(StockbrokerEmailAddressId id, Stockbroker stockbroker) {
       this.id = id;
       this.stockbroker = stockbroker;
    }
   
    public StockbrokerEmailAddressId getId() {
        return this.id;
    }
    
    public void setId(StockbrokerEmailAddressId id) {
        this.id = id;
    }
    public Stockbroker getStockbroker() {
        return this.stockbroker;
    }
    
    public void setStockbroker(Stockbroker stockbroker) {
        this.stockbroker = stockbroker;
    }




}


