package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * StockbrokerPhoneNumberId generated by hbm2java
 */
public class StockbrokerPhoneNumberId  implements java.io.Serializable {


     private int stockbrokerId;
     private String phoneNumber;

    public StockbrokerPhoneNumberId() {
    }

    public StockbrokerPhoneNumberId(int stockbrokerId, String phoneNumber) {
       this.stockbrokerId = stockbrokerId;
       this.phoneNumber = phoneNumber;
    }
   
    public int getStockbrokerId() {
        return this.stockbrokerId;
    }
    
    public void setStockbrokerId(int stockbrokerId) {
        this.stockbrokerId = stockbrokerId;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StockbrokerPhoneNumberId) ) return false;
		 StockbrokerPhoneNumberId castOther = ( StockbrokerPhoneNumberId ) other; 
         
		 return (this.getStockbrokerId()==castOther.getStockbrokerId())
 && ( (this.getPhoneNumber()==castOther.getPhoneNumber()) || ( this.getPhoneNumber()!=null && castOther.getPhoneNumber()!=null && this.getPhoneNumber().equals(castOther.getPhoneNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStockbrokerId();
         result = 37 * result + ( getPhoneNumber() == null ? 0 : this.getPhoneNumber().hashCode() );
         return result;
   }   


}


