package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * StockbrokerSignature generated by hbm2java
 */
public class StockbrokerSignature  implements java.io.Serializable {


     private int id;
     private Stockbroker stockbroker;
     private String signaturePath;
     private boolean stockbrokerSignPrimary;

    public StockbrokerSignature() {
    }

    public StockbrokerSignature(Stockbroker stockbroker, String signaturePath, boolean stockbrokerSignPrimary) {
       this.stockbroker = stockbroker;
       this.signaturePath = signaturePath;
       this.stockbrokerSignPrimary = stockbrokerSignPrimary;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Stockbroker getStockbroker() {
        return this.stockbroker;
    }
    
    public void setStockbroker(Stockbroker stockbroker) {
        this.stockbroker = stockbroker;
    }
    public String getSignaturePath() {
        return this.signaturePath;
    }
    
    public void setSignaturePath(String signaturePath) {
        this.signaturePath = signaturePath;
    }
    public boolean isStockbrokerSignPrimary() {
        return this.stockbrokerSignPrimary;
    }
    
    public void setStockbrokerSignPrimary(boolean stockbrokerSignPrimary) {
        this.stockbrokerSignPrimary = stockbrokerSignPrimary;
    }




}


