package org.greenpole.hibernate.entity;
// Generated 29-May-2015 07:34:19 by Hibernate Tools 4.3.1



/**
 * StockbrokerHolderId generated by hbm2java
 */
public class StockbrokerHolderId  implements java.io.Serializable {


     private int stockbrokerId;
     private int holderId;

    public StockbrokerHolderId() {
    }

    public StockbrokerHolderId(int stockbrokerId, int holderId) {
       this.stockbrokerId = stockbrokerId;
       this.holderId = holderId;
    }
   
    public int getStockbrokerId() {
        return this.stockbrokerId;
    }
    
    public void setStockbrokerId(int stockbrokerId) {
        this.stockbrokerId = stockbrokerId;
    }
    public int getHolderId() {
        return this.holderId;
    }
    
    public void setHolderId(int holderId) {
        this.holderId = holderId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StockbrokerHolderId) ) return false;
		 StockbrokerHolderId castOther = ( StockbrokerHolderId ) other; 
         
		 return (this.getStockbrokerId()==castOther.getStockbrokerId())
 && (this.getHolderId()==castOther.getHolderId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStockbrokerId();
         result = 37 * result + this.getHolderId();
         return result;
   }   


}


