package org.greenpole.hibernate.entity;
// Generated 29-May-2015 21:21:44 by Hibernate Tools 4.3.1



/**
 * StockbrokerPhoneNumber generated by hbm2java
 */
public class StockbrokerPhoneNumber  implements java.io.Serializable {


     private StockbrokerPhoneNumberId id;
     private Long version;
     private Stockbroker stockbroker;
     private Boolean isPrimary;

    public StockbrokerPhoneNumber() {
    }

	
    public StockbrokerPhoneNumber(StockbrokerPhoneNumberId id, Stockbroker stockbroker) {
        this.id = id;
        this.stockbroker = stockbroker;
    }
    public StockbrokerPhoneNumber(StockbrokerPhoneNumberId id, Stockbroker stockbroker, Boolean isPrimary) {
       this.id = id;
       this.stockbroker = stockbroker;
       this.isPrimary = isPrimary;
    }
   
    public StockbrokerPhoneNumberId getId() {
        return this.id;
    }
    
    public void setId(StockbrokerPhoneNumberId id) {
        this.id = id;
    }
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    public Stockbroker getStockbroker() {
        return this.stockbroker;
    }
    
    public void setStockbroker(Stockbroker stockbroker) {
        this.stockbroker = stockbroker;
    }
    public Boolean getIsPrimary() {
        return this.isPrimary;
    }
    
    public void setIsPrimary(Boolean isPrimary) {
        this.isPrimary = isPrimary;
    }




}


