package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SuspendedTransaction generated by hbm2java
 */
public class SuspendedTransaction  implements java.io.Serializable {


     private int id;
     private long versionId;
     private ClientCompany clientCompany;
     private int cscsTransactionId;
     private Date transactionDate;
     private Date suspensionDate;
     private String suspensionReason;
     private boolean reconciled;
     private String companyName;
     private Set suspendedTransactionHolders = new HashSet(0);

    public SuspendedTransaction() {
    }

    public SuspendedTransaction(ClientCompany clientCompany, int cscsTransactionId, Date transactionDate, Date suspensionDate, String suspensionReason, boolean reconciled, String companyName, Set suspendedTransactionHolders) {
       this.clientCompany = clientCompany;
       this.cscsTransactionId = cscsTransactionId;
       this.transactionDate = transactionDate;
       this.suspensionDate = suspensionDate;
       this.suspensionReason = suspensionReason;
       this.reconciled = reconciled;
       this.companyName = companyName;
       this.suspendedTransactionHolders = suspendedTransactionHolders;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
       /**
     * A getter for SuspendedTransaction object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for SuspendedTransaction object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public ClientCompany getClientCompany() {
        return this.clientCompany;
    }
    
    public void setClientCompany(ClientCompany clientCompany) {
        this.clientCompany = clientCompany;
    }
    public int getCscsTransactionId() {
        return this.cscsTransactionId;
    }
    
    public void setCscsTransactionId(int cscsTransactionId) {
        this.cscsTransactionId = cscsTransactionId;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public Date getSuspensionDate() {
        return this.suspensionDate;
    }
    
    public void setSuspensionDate(Date suspensionDate) {
        this.suspensionDate = suspensionDate;
    }
    public String getSuspensionReason() {
        return this.suspensionReason;
    }
    
    public void setSuspensionReason(String suspensionReason) {
        this.suspensionReason = suspensionReason;
    }
    public boolean isReconciled() {
        return this.reconciled;
    }
    
    public void setReconciled(boolean reconciled) {
        this.reconciled = reconciled;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public Set getSuspendedTransactionHolders() {
        return this.suspendedTransactionHolders;
    }
    
    public void setSuspendedTransactionHolders(Set suspendedTransactionHolders) {
        this.suspendedTransactionHolders = suspendedTransactionHolders;
    }




}


