package org.greenpole.hibernate.entity;
// Generated 24-Jun-2015 14:34:48 by Hibernate Tools 4.3.1



/**
 * TextMessage generated by hbm2java
 */
public class TextMessage  implements java.io.Serializable {


     private int id;
     private Long version;
     private Holder holder;
     private String sender;
     private String receiver;
     private String text;
     private String messageId;
     private String purpose;
     private Boolean isBulk;
     private Boolean isFlash;
     private Integer returnCode;
     private Boolean sent;

    public TextMessage() {
    }

    public TextMessage(Holder holder, String sender, String receiver, String text, String messageId, String purpose, Boolean isBulk, Boolean isFlash, Integer returnCode, Boolean sent) {
       this.holder = holder;
       this.sender = sender;
       this.receiver = receiver;
       this.text = text;
       this.messageId = messageId;
       this.purpose = purpose;
       this.isBulk = isBulk;
       this.isFlash = isFlash;
       this.returnCode = returnCode;
       this.sent = sent;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }
    public Holder getHolder() {
        return this.holder;
    }
    
    public void setHolder(Holder holder) {
        this.holder = holder;
    }
    public String getSender() {
        return this.sender;
    }
    
    public void setSender(String sender) {
        this.sender = sender;
    }
    public String getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public String getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }
    public String getPurpose() {
        return this.purpose;
    }
    
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }
    public Boolean getIsBulk() {
        return this.isBulk;
    }
    
    public void setIsBulk(Boolean isBulk) {
        this.isBulk = isBulk;
    }
    public Boolean getIsFlash() {
        return this.isFlash;
    }
    
    public void setIsFlash(Boolean isFlash) {
        this.isFlash = isFlash;
    }
    public Integer getReturnCode() {
        return this.returnCode;
    }
    
    public void setReturnCode(Integer returnCode) {
        this.returnCode = returnCode;
    }
    public Boolean getSent() {
        return this.sent;
    }
    
    public void setSent(Boolean sent) {
        this.sent = sent;
    }




}


