package org.greenpole.hibernate.entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VotingProcess generated by hbm2java
 */
public class VotingProcess  implements java.io.Serializable {


     private int id;
     private long versionId;
     private Gm gm;
     private String title;
     private String notes;
     private Set holderVotings = new HashSet(0);

    public VotingProcess() {
    }

    public VotingProcess(Gm gm, String title, String notes, Set holderVotings) {
       this.gm = gm;
       this.title = title;
       this.notes = notes;
       this.holderVotings = holderVotings;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
     /**
     * A getter for VotingProcess object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for VotingProcess object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public Gm getGm() {
        return this.gm;
    }
    
    public void setGm(Gm gm) {
        this.gm = gm;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public Set getHolderVotings() {
        return this.holderVotings;
    }
    
    public void setHolderVotings(Set holderVotings) {
        this.holderVotings = holderVotings;
    }




}


