package org.greenpole.hibernate.backup_entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1

import org.greenpole.hibernate.entity.*;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * AdministratorEmailAddressId generated by hbm2java
 */
public class AdministratorEmailAddressId  implements java.io.Serializable {


     private int administratorId;
     private long versionId;
     private String emailAddress;
     private int lineNumber;

    public AdministratorEmailAddressId() {
    }

    public AdministratorEmailAddressId(int administratorId, String emailAddress, int lineNumber) {
       this.administratorId = administratorId;
       this.emailAddress = emailAddress;
       this.lineNumber = lineNumber;
    }
   
    public int getAdministratorId() {
        return this.administratorId;
    }
    
    public void setAdministratorId(int administratorId) {
        this.administratorId = administratorId;
    }
     /**
     * A getter for AdministratorEmailAddressId object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for AdministratorEmailAddressId object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public int getLineNumber() {
        return this.lineNumber;
    }
    
    public void setLineNumber(int lineNumber) {
        this.lineNumber = lineNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AdministratorEmailAddressId) ) return false;
		 AdministratorEmailAddressId castOther = ( AdministratorEmailAddressId ) other; 
         
		 return (this.getAdministratorId()==castOther.getAdministratorId())
 && ( (this.getEmailAddress()==castOther.getEmailAddress()) || ( this.getEmailAddress()!=null && castOther.getEmailAddress()!=null && this.getEmailAddress().equals(castOther.getEmailAddress()) ) )
 && (this.getLineNumber()==castOther.getLineNumber());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAdministratorId();
         result = 37 * result + ( getEmailAddress() == null ? 0 : this.getEmailAddress().hashCode() );
         result = 37 * result + this.getLineNumber();
         return result;
   }   


}


