package org.greenpole.hibernate.backup_entity;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1

import org.greenpole.hibernate.entity.*;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1



/**
 * AdministratorPhoneNumber generated by hbm2java
 */
public class AdministratorPhoneNumber  implements java.io.Serializable {


     private AdministratorPhoneNumberId id;
     private Administrator administrator;

    public AdministratorPhoneNumber() {
    }

    public AdministratorPhoneNumber(AdministratorPhoneNumberId id, Administrator administrator) {
       this.id = id;
       this.administrator = administrator;
    }
   
    public AdministratorPhoneNumberId getId() {
        return this.id;
    }
    
    public void setId(AdministratorPhoneNumberId id) {
        this.id = id;
    }
    public Administrator getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(Administrator administrator) {
        this.administrator = administrator;
    }




}


