package org.greenpole.hibernate.backup_entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1

import org.greenpole.hibernate.entity.*;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * AdministratorEmailAddress generated by hbm2java
 */
public class AdministratorEmailAddress  implements java.io.Serializable {


     private AdministratorEmailAddressId id;
     private long versionId;
     private Administrator administrator;

    public AdministratorEmailAddress() {
    }

    public AdministratorEmailAddress(AdministratorEmailAddressId id, Administrator administrator) {
       this.id = id;
       this.administrator = administrator;
    }
   
    public AdministratorEmailAddressId getId() {
        return this.id;
    }
    
    public void setId(AdministratorEmailAddressId id) {
        this.id = id;
    }
    /**
     * A getter for AdministratorEmailAddress object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for AdministratorEmailAddress object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public Administrator getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(Administrator administrator) {
        this.administrator = administrator;
    }




}


