package org.greenpole.hibernate.backup_entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1

import org.greenpole.hibernate.entity.*;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * ClientCompanyPhoneNumberId generated by hbm2java
 */
public class ClientCompanyPhoneNumberId  implements java.io.Serializable {


     private int clientCompanyId;
     private long versionId;
     private String phoneNumber;
     private int lineNumber;

    public ClientCompanyPhoneNumberId() {
    }

    public ClientCompanyPhoneNumberId(int clientCompanyId, String phoneNumber, int lineNumber) {
       this.clientCompanyId = clientCompanyId;
       this.phoneNumber = phoneNumber;
       this.lineNumber = lineNumber;
    }
   
    public int getClientCompanyId() {
        return this.clientCompanyId;
    }
    
    public void setClientCompanyId(int clientCompanyId) {
        this.clientCompanyId = clientCompanyId;
    }
    
    /**
     * A getter for ClientCompanyPhoneNumberId object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for ClientCompanyPhoneNumberId object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public int getLineNumber() {
        return this.lineNumber;
    }
    
    public void setLineNumber(int lineNumber) {
        this.lineNumber = lineNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClientCompanyPhoneNumberId) ) return false;
		 ClientCompanyPhoneNumberId castOther = ( ClientCompanyPhoneNumberId ) other; 
         
		 return (this.getClientCompanyId()==castOther.getClientCompanyId())
 && ( (this.getPhoneNumber()==castOther.getPhoneNumber()) || ( this.getPhoneNumber()!=null && castOther.getPhoneNumber()!=null && this.getPhoneNumber().equals(castOther.getPhoneNumber()) ) )
 && (this.getLineNumber()==castOther.getLineNumber());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getClientCompanyId();
         result = 37 * result + ( getPhoneNumber() == null ? 0 : this.getPhoneNumber().hashCode() );
         result = 37 * result + this.getLineNumber();
         return result;
   }   


}


