package org.greenpole.hibernate.backup_entity;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1

import org.greenpole.hibernate.entity.*;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1



/**
 * DividendSettlement generated by hbm2java
 */
public class DividendSettlement  implements java.io.Serializable {


     private int id;
     private long versionId;
     private DividendDeclared dividendDeclared;
     private Double totalDivAmtDec;
     private Double totalDivAmtPaid;
     private Double totalDivAmtUnpaid;
     private Double totalDivAmtLeft;
     private int shareholdersPaid;
     private int shareholdersUnpaid;

    public DividendSettlement() {
    }

    public DividendSettlement(DividendDeclared dividendDeclared, Double totalDivAmtDec, Double totalDivAmtPaid, Double totalDivAmtUnpaid, Double totalDivAmtLeft, int shareholdersPaid, int shareholdersUnpaid) {
       this.dividendDeclared = dividendDeclared;
       this.totalDivAmtDec = totalDivAmtDec;
       this.totalDivAmtPaid = totalDivAmtPaid;
       this.totalDivAmtUnpaid = totalDivAmtUnpaid;
       this.totalDivAmtLeft = totalDivAmtLeft;
       this.shareholdersPaid = shareholdersPaid;
       this.shareholdersUnpaid = shareholdersUnpaid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    /**
     * A getter for DividendSettlement object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for DividendSettlement object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    
    public DividendDeclared getDividendDeclared() {
        return this.dividendDeclared;
    }
    
    public void setDividendDeclared(DividendDeclared dividendDeclared) {
        this.dividendDeclared = dividendDeclared;
    }
    public Double getTotalDivAmtDec() {
        return this.totalDivAmtDec;
    }
    
    public void setTotalDivAmtDec(Double totalDivAmtDec) {
        this.totalDivAmtDec = totalDivAmtDec;
    }
    public Double getTotalDivAmtPaid() {
        return this.totalDivAmtPaid;
    }
    
    public void setTotalDivAmtPaid(Double totalDivAmtPaid) {
        this.totalDivAmtPaid = totalDivAmtPaid;
    }
    public Double getTotalDivAmtUnpaid() {
        return this.totalDivAmtUnpaid;
    }
    
    public void setTotalDivAmtUnpaid(Double totalDivAmtUnpaid) {
        this.totalDivAmtUnpaid = totalDivAmtUnpaid;
    }
    public Double getTotalDivAmtLeft() {
        return this.totalDivAmtLeft;
    }
    
    public void setTotalDivAmtLeft(Double totalDivAmtLeft) {
        this.totalDivAmtLeft = totalDivAmtLeft;
    }
    public int getShareholdersPaid() {
        return this.shareholdersPaid;
    }
    
    public void setShareholdersPaid(int shareholdersPaid) {
        this.shareholdersPaid = shareholdersPaid;
    }
    public int getShareholdersUnpaid() {
        return this.shareholdersUnpaid;
    }
    
    public void setShareholdersUnpaid(int shareholdersUnpaid) {
        this.shareholdersUnpaid = shareholdersUnpaid;
    }




}


