package org.greenpole.hibernate.backup_entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1

import org.greenpole.hibernate.entity.*;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * HolderResidentialAddress generated by hbm2java
 */
public class HolderResidentialAddress  implements java.io.Serializable {


     private HolderResidentialAddressId id;
     private long versionId;
     private Holder holder;
     private String type;

    public HolderResidentialAddress() {
    }

	
    public HolderResidentialAddress(HolderResidentialAddressId id, Holder holder) {
        this.id = id;
        this.holder = holder;
    }
    public HolderResidentialAddress(HolderResidentialAddressId id, Holder holder, String type) {
       this.id = id;
       this.holder = holder;
       this.type = type;
    }
   
    public HolderResidentialAddressId getId() {
        return this.id;
    }
    
    public void setId(HolderResidentialAddressId id) {
        this.id = id;
    }
    /**
     * A getter for HolderResidentialAddress object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for HolderResidentialAddress object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public Holder getHolder() {
        return this.holder;
    }
    
    public void setHolder(Holder holder) {
        this.holder = holder;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


