package org.greenpole.hibernate.backup_entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1

import org.greenpole.hibernate.entity.*;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * HolderGmAttendance generated by hbm2java
 */
public class HolderGmAttendance  implements java.io.Serializable {


     private HolderGmAttendanceId id;
     private long versionId;
     private Gm gm;
     private Holder holder;
     private String proxy;

    public HolderGmAttendance() {
    }

	
    public HolderGmAttendance(HolderGmAttendanceId id, Gm gm, Holder holder) {
        this.id = id;
        this.gm = gm;
        this.holder = holder;
    }
    public HolderGmAttendance(HolderGmAttendanceId id, Gm gm, Holder holder, String proxy) {
       this.id = id;
       this.gm = gm;
       this.holder = holder;
       this.proxy = proxy;
    }
   
    public HolderGmAttendanceId getId() {
        return this.id;
    }
    
    public void setId(HolderGmAttendanceId id) {
        this.id = id;
    }
    /**
     * A getter for HolderGmAttendance object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for HolderGmAttendance object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public Gm getGm() {
        return this.gm;
    }
    
    public void setGm(Gm gm) {
        this.gm = gm;
    }
    public Holder getHolder() {
        return this.holder;
    }
    
    public void setHolder(Holder holder) {
        this.holder = holder;
    }
    public String getProxy() {
        return this.proxy;
    }
    
    public void setProxy(String proxy) {
        this.proxy = proxy;
    }




}


