package org.greenpole.hibernate.backup_entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1

import org.greenpole.hibernate.entity.*;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * HolderEmailAddressId generated by hbm2java
 */
public class HolderEmailAddressId  implements java.io.Serializable {


     private int holderId;
     private long versionId;
     private String emailAddress;
     private int lineNumber;

    public HolderEmailAddressId() {
    }

    public HolderEmailAddressId(int holderId, String emailAddress, int lineNumber) {
       this.holderId = holderId;
       this.emailAddress = emailAddress;
       this.lineNumber = lineNumber;
    }
   
    public int getHolderId() {
        return this.holderId;
    }
    /**
     * A getter for HolderEmailAddressId object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for HolderEmailAddressId object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }
    public void setHolderId(int holderId) {
        this.holderId = holderId;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public int getLineNumber() {
        return this.lineNumber;
    }
    
    public void setLineNumber(int lineNumber) {
        this.lineNumber = lineNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HolderEmailAddressId) ) return false;
		 HolderEmailAddressId castOther = ( HolderEmailAddressId ) other; 
         
		 return (this.getHolderId()==castOther.getHolderId())
 && ( (this.getEmailAddress()==castOther.getEmailAddress()) || ( this.getEmailAddress()!=null && castOther.getEmailAddress()!=null && this.getEmailAddress().equals(castOther.getEmailAddress()) ) )
 && (this.getLineNumber()==castOther.getLineNumber());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getHolderId();
         result = 37 * result + ( getEmailAddress() == null ? 0 : this.getEmailAddress().hashCode() );
         result = 37 * result + this.getLineNumber();
         return result;
   }   


}


