package org.greenpole.hibernate.backup_entity;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1

import org.greenpole.hibernate.entity.*;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1



/**
 * StockbrokerPhoneNumber generated by hbm2java
 */
public class StockbrokerPhoneNumber  implements java.io.Serializable {


     private StockbrokerPhoneNumberId id;
     private Stockbroker stockbroker;

    public StockbrokerPhoneNumber() {
    }

    public StockbrokerPhoneNumber(StockbrokerPhoneNumberId id, Stockbroker stockbroker) {
       this.id = id;
       this.stockbroker = stockbroker;
    }
   
    public StockbrokerPhoneNumberId getId() {
        return this.id;
    }
    
    public void setId(StockbrokerPhoneNumberId id) {
        this.id = id;
    }
    public Stockbroker getStockbroker() {
        return this.stockbroker;
    }
    
    public void setStockbroker(Stockbroker stockbroker) {
        this.stockbroker = stockbroker;
    }




}


