package org.greenpole.hibernate.backup_entity;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1

import org.greenpole.hibernate.entity.*;
// Generated Apr 2, 2015 11:49:14 AM by Hibernate Tools 4.3.1



/**
 * SuspendedTransactionHolderId generated by hbm2java
 */
public class SuspendedTransactionHolderId  implements java.io.Serializable {


     private int transactionId;
     private int holderId;
     private long versionId;

    public SuspendedTransactionHolderId() {
    }

    public SuspendedTransactionHolderId(int transactionId, int holderId) {
       this.transactionId = transactionId;
       this.holderId = holderId;
    }
   
    public int getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }
    public int getHolderId() {
        return this.holderId;
    }
    
    public void setHolderId(int holderId) {
        this.holderId = holderId;
    }
      /**
     * A getter for SuspendedTransactionHolderId object which retrieve 
     * a version identifier, apart from the primary key of object
     * @return versionId identifier
     */
    public long getVersionId() {
        return versionId;
    }
    /**
     * A setter for SuspendedTransactionHolderId object which persist the 
     * versionId identifier in the memory by hibernate
     * @param versionId, an argument that receives the generated 
     * version of current object by hibernate
     */
    public void setVersionId(long versionId) {
        this.versionId = versionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SuspendedTransactionHolderId) ) return false;
		 SuspendedTransactionHolderId castOther = ( SuspendedTransactionHolderId ) other; 
         
		 return (this.getTransactionId()==castOther.getTransactionId())
 && (this.getHolderId()==castOther.getHolderId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTransactionId();
         result = 37 * result + this.getHolderId();
         return result;
   }   


}


