package org.greenpole.hibernate.entrypoint;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1



/**
 * Caution generated by hbm2java
 */
public class Caution  implements java.io.Serializable {


     private int id;
     private Holder holder;
     private String title;
     private String description;
     private String type;
     private boolean active;

    public Caution() {
    }

    public Caution(Holder holder, String title, String description, String type, boolean active) {
       this.holder = holder;
       this.title = title;
       this.description = description;
       this.type = type;
       this.active = active;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Holder getHolder() {
        return this.holder;
    }
    
    public void setHolder(Holder holder) {
        this.holder = holder;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }




}


