package org.greenpole.hibernate.entrypoint;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1



/**
 * ClientCompanyPhoneNumber generated by hbm2java
 */
public class ClientCompanyPhoneNumber  implements java.io.Serializable {


     private ClientCompanyPhoneNumberId id;
     private ClientCompany clientCompany;

    public ClientCompanyPhoneNumber() {
    }

    public ClientCompanyPhoneNumber(ClientCompanyPhoneNumberId id, ClientCompany clientCompany) {
       this.id = id;
       this.clientCompany = clientCompany;
    }
   
    public ClientCompanyPhoneNumberId getId() {
        return this.id;
    }
    
    public void setId(ClientCompanyPhoneNumberId id) {
        this.id = id;
    }
    public ClientCompany getClientCompany() {
        return this.clientCompany;
    }
    
    public void setClientCompany(ClientCompany clientCompany) {
        this.clientCompany = clientCompany;
    }




}


