package org.greenpole.hibernate.entrypoint;
// Generated Mar 27, 2015 1:23:05 PM by Hibernate Tools 4.3.1



/**
 * DividenAnnotation generated by hbm2java
 */
public class DividenAnnotation  implements java.io.Serializable {


     private int id;
     private Dividend dividend;
     private String annotation;

    public DividenAnnotation() {
    }

    public DividenAnnotation(Dividend dividend, String annotation) {
       this.dividend = dividend;
       this.annotation = annotation;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Dividend getDividend() {
        return this.dividend;
    }
    
    public void setDividend(Dividend dividend) {
        this.dividend = dividend;
    }
    public String getAnnotation() {
        return this.annotation;
    }
    
    public void setAnnotation(String annotation) {
        this.annotation = annotation;
    }




}


